# -*- coding: utf-8 -*-
"""weather pipeline project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tnh6tzMrirQUBD5ERCRtFZHEx0wMQw0r
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Display descriptive statistics for numerical columns
print("\nDescriptive Statistics for Numerical Features:")
display(df_house_prices.describe())

# Set the aesthetic style of the plots
sns.set_style("whitegrid")

# Create histograms for numerical features to visualize their distributions
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('Distributions of Numerical Features', fontsize=16)

sns.histplot(df_house_prices['Area'], kde=True, ax=axes[0, 0], color='skyblue')
axes[0, 0].set_title('Distribution of Area')

sns.histplot(df_house_prices['Bedrooms'], kde=True, ax=axes[0, 1], color='lightcoral')
axes[0, 1].set_title('Distribution of Bedrooms')

sns.histplot(df_house_prices['Bathrooms'], kde=True, ax=axes[0, 2], color='lightgreen')
axes[0, 2].set_title('Distribution of Bathrooms')

sns.histplot(df_house_prices['Age'], kde=True, ax=axes[1, 0], color='lightgoldenrodyellow')
axes[1, 0].set_title('Distribution of Age')

sns.histplot(df_house_prices['Price'], kde=True, ax=axes[1, 1], color='lightsalmon')
axes[1, 1].set_title('Distribution of Price')

# Remove unused subplot
fig.delaxes(axes[1, 2])

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Define features (X) and target (y)
# 'Property_ID' is an identifier and not a feature, so we drop it.
X = df_processed.drop(['Property_ID', 'Price'], axis=1)
y = df_processed['Price']

# Identify numerical columns for scaling (excluding the newly created one-hot encoded columns which are already binary)
numerical_cols = ['Area', 'Bedrooms', 'Bathrooms', 'Age']

# Initialize StandardScaler
scaler = StandardScaler()

# Apply scaling to numerical columns
X[numerical_cols] = scaler.fit_transform(X[numerical_cols])

print("Features (X) after scaling (first 5 rows):")
display(X.head())

print("Target (y) after processing (first 5 rows):")
display(y.head())

# Split the data into training and testing sets
# We'll use a test size of 20% and a random state for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nShape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# Initialize the Linear Regression model
linear_model = LinearRegression()

# Train the model using the training data
linear_model.fit(X_train, y_train)

print("Linear Regression Model trained successfully.")

# Make predictions on the test set
y_pred = linear_model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\nModel Evaluation:")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"R-squared (R2): {r2:.2f}")

# Optionally, visualize predictions vs actuals
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs. Predicted Prices (Linear Regression)")
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], color='red', linestyle='--') # Perfect prediction line
plt.show()

import pandas as pd

# Identify categorical columns for one-hot encoding
categorical_cols = ['Location', 'Property_Type']

# Apply one-hot encoding
df_processed = pd.get_dummies(df_house_prices, columns=categorical_cols, drop_first=True)

print("DataFrame after One-Hot Encoding:")
display(df_processed.head())
print(f"New shape of DataFrame: {df_processed.shape}")
print("Columns after encoding:")
print(df_processed.columns.tolist())

"""#### Relationship between Numerical Features and Price

Let's visualize how other numerical features relate to the 'Price' using scatter plots.
"""

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 4, figsize=(24, 6))
fig.suptitle('Relationship of Numerical Features with Price', fontsize=16)

sns.scatterplot(x='Area', y='Price', data=df_house_prices, ax=axes[0], color='skyblue')
axes[0].set_title('Area vs. Price')

sns.scatterplot(x='Bedrooms', y='Price', data=df_house_prices, ax=axes[1], color='lightcoral')
axes[1].set_title('Bedrooms vs. Price')

sns.scatterplot(x='Bathrooms', y='Price', data=df_house_prices, ax=axes[2], color='lightgreen')
axes[2].set_title('Bathrooms vs. Price')

sns.scatterplot(x='Age', y='Price', data=df_house_prices, ax=axes[3], color='lightgoldenrodyellow')
axes[3].set_title('Age vs. Price')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""#### Distribution of Categorical Features

Now, let's look at the distribution of the categorical features: 'Location' and 'Property_Type'.
"""

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Distributions of Categorical Features', fontsize=16)

sns.countplot(x='Location', data=df_house_prices, ax=axes[0], palette='viridis', hue='Location', legend=False)
axes[0].set_title('Distribution of Location')
axes[0].tick_params(axis='x', rotation=45)

sns.countplot(x='Property_Type', data=df_house_prices, ax=axes[1], palette='plasma', hue='Property_Type', legend=False)
axes[1].set_title('Distribution of Property_Type')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""#### Price Variation by Categorical Features

Let's examine how the 'Price' varies across different 'Location' and 'Property_Type' categories using box plots.
"""

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Price Variation by Categorical Features', fontsize=16)

sns.boxplot(x='Location', y='Price', data=df_house_prices, ax=axes[0], palette='viridis', hue='Location', legend=False)
axes[0].set_title('Price by Location')
axes[0].tick_params(axis='x', rotation=45)

sns.boxplot(x='Property_Type', y='Price', data=df_house_prices, ax=axes[1], palette='plasma', hue='Property_Type', legend=False)
axes[1].set_title('Price by Property Type')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""### Summary of EDA Observations

After reviewing the plots, we can make initial observations regarding the distributions and relationships within the house prices data. This information is crucial for guiding subsequent data preprocessing and model building steps. For example, we might notice skewness in 'Price' or 'Area' which could suggest a need for transformations, or observe a strong correlation between 'Area' and 'Price'.
"""